### PR TITLE
feat: add `/similarity` route

### PR DESCRIPTION
**Pull request by OlivierDehaene**
Required for compatibility.

### CODE REVIEW

**Comment by cordawyn** [comment]
@OlivierDehaene Would it make sense to make it compatible with huggingface-hub client: https://github.com/huggingface/huggingface_hub/blob/ca111fb51193968faed548a4b865c79736822aed/src/huggingface_hub/inference/_client.py#L1416 ? It looks like they expect a bit different names for the attributes of `SimilarityInput` (https://github.com/huggingface/text-embeddings-inference/blob/4cc38bda85b2ecdbf34082796ca9738466483b85/router/src/http/types.rs#L364).

**Comment by OlivierDehaene** [comment]
What do you mean? It is compatible.

**Comment by OlivierDehaene** [comment]
The payload is: https://github.com/huggingface/huggingface_hub/blob/ca111fb51193968faed548a4b865c79736822aed/src/huggingface_hub/inference/_client.py#L1457

which is what we expect here.

**Comment by cordawyn** [comment]
Oh, my apologies. I must've looked at a different revision or something. Thanks for the quick reply!

**Pull request merged**
